import { motion } from "framer-motion";
import {
  Sparkles,
  Lightbulb,
  ArrowUpRight,
  CheckCircle2,
} from "lucide-react";

interface SuggestionsProps {
  suggestions: string[];
}

export default function Suggestions({
  suggestions,
}: SuggestionsProps) {
  return (
    <motion.section
      initial={{ opacity: 0, y: 15 }}
      animate={{ opacity: 1, y: 0 }}
      className="rounded-3xl border bg-white p-8 shadow-sm"
    >
      <div className="mb-8 flex items-center justify-between">

        <div>

          <h2 className="text-2xl font-bold">
            AI Suggestions
          </h2>

          <p className="mt-2 text-sm text-muted-foreground">
            Personalized recommendations generated by AI to improve
            your resume and increase your ATS score.
          </p>

        </div>

        <div className="rounded-2xl bg-violet-100 p-4">

          <Sparkles className="h-8 w-8 text-violet-600" />

        </div>

      </div>

      {suggestions.length === 0 ? (
        <div className="flex flex-col items-center justify-center rounded-2xl border border-dashed py-16">

          <CheckCircle2 className="mb-5 h-10 w-10 text-green-600" />

          <h3 className="text-lg font-semibold">
            Excellent Resume
          </h3>

          <p className="mt-2 max-w-md text-center text-sm text-muted-foreground">
            We couldn't find any significant improvements.
            Your resume already follows most ATS best practices.
          </p>

        </div>
      ) : (
        <div className="space-y-5">

          {suggestions.map((suggestion, index) => (
            <motion.div
              key={index}
              initial={{
                opacity: 0,
                y: 15,
              }}
              animate={{
                opacity: 1,
                y: 0,
              }}
              transition={{
                delay: index * 0.08,
              }}
              whileHover={{
                y: -2,
              }}
              className="rounded-2xl border bg-slate-50 p-6 transition-colors hover:border-blue-300 hover:bg-blue-50"
            >
              <div className="flex gap-5">

                <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-blue-600 text-lg font-bold text-white">

                  {index + 1}

                </div>

                <div className="flex-1">

                  <div className="mb-3 flex items-center gap-2">

                    <Lightbulb className="h-5 w-5 text-yellow-500" />

                    <h3 className="font-semibold">
                      Recommendation {index + 1}
                    </h3>

                  </div>

                  <p className="leading-7 text-muted-foreground">
                    {suggestion}
                  </p>

                </div>

                <ArrowUpRight className="h-5 w-5 text-blue-600" />

              </div>
            </motion.div>
          ))}

        </div>
      )}

      <div className="mt-8 rounded-2xl bg-gradient-to-r from-blue-600 to-violet-600 p-6 text-white">

        <div className="flex items-start gap-4">

          <Sparkles className="mt-1 h-6 w-6 shrink-0" />

          <div>

            <h3 className="text-lg font-semibold">
              AI Insight
            </h3>

            <p className="mt-2 text-sm leading-7 text-blue-100">
              Even small improvements such as adding measurable
              achievements, relevant technical keywords, and
              stronger action verbs can significantly improve ATS
              performance and recruiter engagement.
            </p>

          </div>

        </div>

      </div>
    </motion.section>
  );
}