import { useMemo } from "react";

import { motion } from "framer-motion";

import {
  Sparkles,
  Lightbulb,
  ArrowUpRight,
  CheckCircle2,
  Target,
  TrendingUp,
  FileSearch,
  Briefcase,
  GraduationCap,
  Wrench,
 
} from "lucide-react";

interface SuggestionsProps {
  suggestions: string[];
}

interface SuggestionCard {
  title: string;
  icon: React.ReactNode;
  color: string;
  background: string;
  badge: string;
  improvement: number;
}

export default function Suggestions({
  suggestions,
}: SuggestionsProps) {

  const categories: SuggestionCard[] = [

    {
      title: "Keyword Optimization",
      icon: (
        <Target className="h-5 w-5"/>
      ),
      color: "text-blue-600",
      background: "bg-blue-100",
      badge: "High",
      improvement: 6,
    },

    {
      title: "Formatting",
      icon: (
        <FileSearch className="h-5 w-5"/>
      ),
      color: "text-violet-600",
      background: "bg-violet-100",
      badge: "Medium",
      improvement: 4,
    },

    {
      title: "Projects",
      icon: (
        <Briefcase className="h-5 w-5"/>
      ),
      color: "text-emerald-600",
      background: "bg-emerald-100",
      badge: "Medium",
      improvement: 5,
    },

    {
      title: "Skills",
      icon: (
        <Wrench className="h-5 w-5"/>
      ),
      color: "text-amber-600",
      background: "bg-amber-100",
      badge: "Low",
      improvement: 3,
    },

    {
      title: "Education",
      icon: (
        <GraduationCap className="h-5 w-5"/>
      ),
      color: "text-pink-600",
      background: "bg-pink-100",
      badge: "Low",
      improvement: 2,
    },

  ];

  const estimatedGain = useMemo(() => {

    return Math.min(
      suggestions.length * 3,
      15
    );

  }, [suggestions]);

  return (

    <motion.section

      initial={{
        opacity: 0,
        y: 20,
      }}

      animate={{
        opacity: 1,
        y: 0,
      }}

      transition={{
        duration: .35,
      }}

      className="rounded-[30px] border bg-white p-8 shadow-sm"

    >

      {/* Header */}

      <div className="mb-8 flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between">

        <div>

          <div className="flex items-center gap-4">

            <div className="rounded-2xl bg-violet-100 p-4">

              <Sparkles className="h-7 w-7 text-violet-600"/>

            </div>

            <div>

              <h2 className="text-3xl font-bold tracking-tight">

                AI Resume Suggestions

              </h2>

              <p className="mt-2 max-w-2xl text-sm leading-7 text-muted-foreground">

                Personalized recommendations
                generated by InterviewIQ AI
                to improve ATS compatibility,
                recruiter visibility,
                and interview success.

              </p>

            </div>

          </div>

        </div>

        <div className="hidden rounded-2xl border bg-slate-50 p-5 lg:block">

          <div className="flex items-center gap-3">

            <TrendingUp className="h-5 w-5 text-blue-600"/>

            <div>

              <p className="font-semibold">

                Estimated ATS Gain

              </p>

              <p className="text-xs text-muted-foreground">

                +{estimatedGain} Points

              </p>

            </div>

          </div>

        </div>

      </div>

      {suggestions.length === 0 ? (

        <motion.div
          initial={{
            opacity: 0,
            scale: .95,
          }}
          animate={{
            opacity: 1,
            scale: 1,
          }}
          className="rounded-[28px] border border-dashed bg-gradient-to-br from-green-50 to-white p-12 text-center"
        >

          <div className="mx-auto flex h-20 w-20 items-center justify-center rounded-full bg-green-100">

            <CheckCircle2 className="h-10 w-10 text-green-600"/>

          </div>

          <h3 className="mt-8 text-3xl font-bold">

            Outstanding Resume

          </h3>

          <p className="mx-auto mt-4 max-w-xl leading-8 text-muted-foreground">

            InterviewIQ AI couldn't find any
            major ATS issues.

            Your resume already follows
            modern recruiter and ATS best
            practices.

          </p>

          <div className="mt-10 inline-flex rounded-full bg-green-100 px-6 py-3 text-sm font-semibold text-green-700">

            Ready for Applications 🚀

          </div>

        </motion.div>

      ) : (

        <>

          {/* Summary Cards */}

          <div className="grid gap-6 lg:grid-cols-3">
                        <motion.div
              initial={{
                opacity: 0,
                y: 20,
              }}
              animate={{
                opacity: 1,
                y: 0,
              }}
              className="rounded-3xl border bg-gradient-to-br from-blue-50 to-white p-6"
            >

              <div className="flex items-center gap-3">

                <TrendingUp className="h-6 w-6 text-blue-600"/>

                <div>

                  <p className="text-sm text-muted-foreground">
                    Potential ATS Gain
                  </p>

                  <h3 className="text-3xl font-bold">
                    +{estimatedGain}
                  </h3>

                </div>

              </div>

              <p className="mt-5 text-sm leading-6 text-muted-foreground">

                Applying these recommendations
                can significantly improve recruiter
                visibility and ATS performance.

              </p>

            </motion.div>

            <motion.div
              initial={{
                opacity: 0,
                y: 20,
              }}
              animate={{
                opacity: 1,
                y: 0,
              }}
              transition={{
                delay: .1,
              }}
              className="rounded-3xl border bg-gradient-to-br from-violet-50 to-white p-6"
            >

              <div className="flex items-center gap-3">

                <Sparkles className="h-6 w-6 text-violet-600"/>

                <div>

                  <p className="text-sm text-muted-foreground">

                    AI Confidence

                  </p>

                  <h3 className="text-3xl font-bold">

                    98%

                  </h3>

                </div>

              </div>

              <p className="mt-5 text-sm leading-6 text-muted-foreground">

                These recommendations are
                generated using AI analysis
                trained on ATS best practices
                and recruiter expectations.

              </p>

            </motion.div>

            <motion.div
              initial={{
                opacity: 0,
                y: 20,
              }}
              animate={{
                opacity: 1,
                y: 0,
              }}
              transition={{
                delay: .2,
              }}
              className="rounded-3xl border bg-gradient-to-br from-emerald-50 to-white p-6"
            >

              <div className="flex items-center gap-3">

                <CheckCircle2 className="h-6 w-6 text-emerald-600"/>

                <div>

                  <p className="text-sm text-muted-foreground">

                    Suggestions

                  </p>

                  <h3 className="text-3xl font-bold">

                    {suggestions.length}

                  </h3>

                </div>

              </div>

              <p className="mt-5 text-sm leading-6 text-muted-foreground">

                High-quality recommendations
                prioritized by expected impact
                on ATS optimization.

              </p>

            </motion.div>

          </div>

          {/* AI Suggestions */}

          <div className="mt-10 space-y-6">

            {suggestions.map((suggestion, index) => {

              const category =
                categories[
                  index %
                  categories.length
                ];

              return (

                <motion.div
                  key={suggestion}
                  initial={{
                    opacity: 0,
                    y: 20,
                  }}
                  animate={{
                    opacity: 1,
                    y: 0,
                  }}
                  transition={{
                    delay:
                      index * .08,
                  }}
                  whileHover={{
                    y: -4,
                  }}
                  className="rounded-3xl border bg-white p-7 shadow-sm transition-all"
                >

                  <div className="flex flex-col gap-6 lg:flex-row lg:items-start">

                    <div
                      className={`rounded-2xl p-4 ${category.background}`}
                    >

                      <div
                        className={category.color}
                      >

                        {category.icon}

                      </div>

                    </div>

                    <div className="flex-1">

                      <div className="flex flex-wrap items-center gap-3">

                        <h3 className="text-xl font-semibold">

                          {category.title}

                        </h3>

                        <span
                          className={`rounded-full px-3 py-1 text-xs font-semibold ${category.background} ${category.color}`}
                        >

                          {category.badge}

                        </span>

                        <span className="rounded-full bg-blue-100 px-3 py-1 text-xs font-semibold text-blue-700">

                          +{category.improvement} ATS

                        </span>

                      </div>

                      <p className="mt-5 leading-8 text-muted-foreground">

                        {suggestion}

                      </p>

                      <div className="mt-6 flex flex-wrap gap-3">

                        <span className="rounded-full bg-slate-100 px-3 py-2 text-xs font-medium">

                          ATS

                        </span>

                        <span className="rounded-full bg-slate-100 px-3 py-2 text-xs font-medium">

                          Recruiter

                        </span>

                        <span className="rounded-full bg-slate-100 px-3 py-2 text-xs font-medium">

                          AI Verified

                        </span>

                      </div>

                    </div>

                    <div className="flex flex-col items-end">

                      <ArrowUpRight
                        className={`h-6 w-6 ${category.color}`}
                      />

                      <p className="mt-3 text-xs text-muted-foreground">

                        Priority

                      </p>

                      <p
                        className={`font-semibold ${category.color}`}
                      >

                        {category.badge}

                      </p>

                    </div>

                  </div>

                </motion.div>

              );

            })}

          </div>
                    {/* Resume Health Dashboard */}

          <motion.div
            initial={{
              opacity: 0,
              y: 20,
            }}
            animate={{
              opacity: 1,
              y: 0,
            }}
            transition={{
              delay: 0.45,
            }}
            className="mt-10 rounded-3xl border bg-white p-7 shadow-sm"
          >

            <div className="mb-7 flex items-center gap-3">

              <TrendingUp className="h-6 w-6 text-blue-600"/>

              <div>

                <h3 className="text-xl font-semibold">
                  Resume Health
                </h3>

                <p className="text-sm text-muted-foreground">
                  Estimated quality across key ATS categories.
                </p>

              </div>

            </div>

            <div className="space-y-6">

              {[
                {
                  label: "Formatting",
                  value: 92,
                },
                {
                  label: "Keywords",
                  value: 84,
                },
                {
                  label: "Projects",
                  value: 81,
                },
                {
                  label: "Experience",
                  value: 88,
                },
                {
                  label: "Skills",
                  value: 86,
                },
              ].map((item, index) => (

                <div key={item.label}>

                  <div className="mb-2 flex items-center justify-between">

                    <span className="font-medium">

                      {item.label}

                    </span>

                    <span className="text-sm font-semibold">

                      {item.value}%

                    </span>

                  </div>

                  <div className="h-2 overflow-hidden rounded-full bg-slate-200">

                    <motion.div
                      initial={{
                        width: 0,
                      }}
                      animate={{
                        width: `${item.value}%`,
                      }}
                      transition={{
                        duration: 1,
                        delay: index * 0.12,
                      }}
                      className="h-full rounded-full bg-gradient-to-r from-blue-600 to-violet-600"
                    />

                  </div>

                </div>

              ))}

            </div>

          </motion.div>

          {/* AI Insight */}

          <motion.div
            initial={{
              opacity: 0,
              y: 20,
            }}
            animate={{
              opacity: 1,
              y: 0,
            }}
            transition={{
              delay: 0.6,
            }}
            className="mt-10 rounded-3xl bg-gradient-to-r from-blue-600 via-indigo-600 to-violet-600 p-8 text-white"
          >

            <div className="flex items-start gap-5">

              <div className="rounded-2xl bg-white/15 p-4 backdrop-blur">

                <Lightbulb className="h-7 w-7"/>

              </div>

              <div>

                <h3 className="text-2xl font-semibold">

                  AI Insight

                </h3>

                <p className="mt-5 leading-8 text-blue-100">

                  Your resume already demonstrates
                  a solid foundation for ATS screening.
                  Implementing the recommendations above
                  can improve keyword relevance,
                  recruiter visibility,
                  and search ranking while increasing
                  interview conversion opportunities.

                </p>

              </div>

            </div>

          </motion.div>

          {/* Forecast */}

          <motion.div
            initial={{
              opacity: 0,
              y: 20,
            }}
            animate={{
              opacity: 1,
              y: 0,
            }}
            transition={{
              delay: 0.75,
            }}
            className="mt-10 rounded-3xl border bg-gradient-to-br from-slate-50 to-white p-7"
          >

            <div className="flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between">

              <div>

                <div className="flex items-center gap-3">

                  <Sparkles className="h-6 w-6 text-violet-600"/>

                  <h3 className="text-xl font-semibold">

                    Improvement Forecast

                  </h3>

                </div>

                <p className="mt-5 max-w-2xl leading-7 text-muted-foreground">

                  Addressing all AI recommendations
                  can substantially improve ATS parsing,
                  recruiter engagement,
                  keyword coverage,
                  and overall resume quality.

                </p>

              </div>

              <div className="rounded-3xl bg-gradient-to-r from-blue-600 to-violet-600 px-8 py-6 text-center text-white">

                <p className="text-sm text-blue-100">

                  Estimated Improvement

                </p>

                <h2 className="mt-2 text-5xl font-bold">

                  +{estimatedGain}

                </h2>

                <p className="mt-2 text-sm text-blue-100">

                  ATS Points

                </p>

              </div>

            </div>

          </motion.div>

        </>

      )}

    </motion.section>

  );

}